[[redirects]]
force = true
from = '/api/*'
status = 200
to = '/.netlify/functions/:splat'

[[redirects]]
from = '/*'
status = 200
to = '/index.html'

[build]
command = 'npm run test && npm run build:netlify && npm run build'
environment = { NODE_VERSION = '14' }
publish = 'dist'
functions = 'dist/functions'

[dev]
autolaunch = false
